services:
  db:
    image: postgres:16
    container_name: news_db
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - news_pgdata:/var/lib/postgresql/data

volumes:
  news_pgdata:  